import { createHash } from 'node:crypto';
import { chmod, mkdir, readFile, symlink, writeFile } from 'node:fs/promises';
import pathModule from 'node:path';

import { describe, expect, it } from 'vitest';
import { z } from 'zod';

import { pseudoRandomBytes } from '../../../../tests/support/bytes.ts';
import { withTemporaryDirectory } from '../../../../tests/support/filesystem.ts';
import { runCommand } from '../../../../tests/support/process.ts';

import {
	hashNar,
	InvalidNixSha256HashError,
	InvalidSha256DigestLengthError,
	NarArchive,
	narFromPath,
	NixSha256Hash,
	toNixBase32,
	toNixSha256,
	UnsupportedNarPathTypeError
} from './nar.ts';

function thrownBy(run: () => unknown): unknown {
	let thrown: unknown;

	try {
		run();
	} catch (error) {
		thrown = error;
	}

	return thrown;
}

describe('narFromPath', () => {
	it('serialises an empty directory', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await expect(narText(directory)).resolves.toBe(
				['nix-archive-1', '(', 'type', 'directory', ')']
					.map((value) => narString(value))
					.join('')
			);
		});
	});

	it('sorts directory entries by byte order', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeFile(pathModule.join(directory, 'b'), 'second');
			await writeFile(pathModule.join(directory, 'a'), 'first');

			const text = await narText(directory);

			expect(text.indexOf(narString('a'))).toBeLessThan(
				text.indexOf(narString('b'))
			);
		});
	});

	it('serialises symlinks and executable files', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			const file = pathModule.join(directory, 'run');
			await writeFile(file, 'hello');
			await chmod(file, 0o755);
			await symlink('run', pathModule.join(directory, 'link'));

			await expect(narText(directory)).resolves.toBe(
				[
					'nix-archive-1',
					'(',
					'type',
					'directory',
					'entry',
					'(',
					'name',
					'link',
					'node',
					'(',
					'type',
					'symlink',
					'target',
					'run',
					')',
					')',
					'entry',
					'(',
					'name',
					'run',
					'node',
					'(',
					'type',
					'regular',
					'executable',
					'',
					'contents',
					'hello',
					')',
					')',
					')'
				]
					.map((value) => narString(value))
					.join('')
			);
		});
	});
});

describe('hashNar', () => {
	it('returns a Nix base32 sha256 hash and NAR size', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeFile(pathModule.join(directory, 'file'), 'hello');

			const bytes = Buffer.concat(await collectNar(directory));
			const expectedHash = toNixSha256(
				createHash('sha256').update(bytes).digest()
			);

			await expect(hashNar(directory)).resolves.toStrictEqual({
				narHash: expectedHash,
				narSize: bytes.byteLength
			});
		});
	});

	it('matches a NAR fixture generated by nix-store --dump', async () => {
		const fixture = await readNarFixture('simple');
		const expectedHash = toNixSha256(Buffer.from(fixture.narSha256, 'hex'));
		const actualBytes = Buffer.concat(await collectNar(fixture.sourcePath));

		expect(actualBytes).toStrictEqual(fixture.narBytes);
		await expect(hashNar(fixture.sourcePath)).resolves.toStrictEqual({
			narHash: expectedHash,
			narSize: fixture.narSize
		});
	});
});

describe('NarArchive', () => {
	it('serialises a tree of many small files exactly as nix-store --dump does', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeNarTree(directory);

			// `nix-store --dump` of this tree produced these values.
			await expect(new NarArchive(directory).hash()).resolves.toStrictEqual({
				narHash: toNixSha256(
					Buffer.from(
						'899032f837d452dcfbc9f96f41df87ee00641030b7849ae489bb01238b4e8381',
						'hex'
					)
				),
				narSize: 11_266_936
			});
		});
	});

	it('lets the event loop run while it reads many small files', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			for (let index = 0; index < 400; index += 1) {
				await writeFile(
					pathModule.join(directory, `f${String(index)}`),
					pseudoRandomBytes(100, index + 1)
				);
			}

			let turns = 0;
			let isIterating = true;
			const countTurn = (): void => {
				if (!isIterating) {
					return;
				}

				turns += 1;
				setImmediate(countTurn);
			};
			setImmediate(countTurn);

			await collect(new NarArchive(directory));
			isIterating = false;

			// The archive lets the event loop run at least once for every 64
			// of the 400 files.
			expect(turns).toBeGreaterThanOrEqual(6);
		});
	});

	it('refuses a node that is not a file, directory or symlink', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			const fifo = pathModule.join(directory, 'fifo');
			await runCommand('mkfifo', [fifo]);

			const error = await rejectionOf(collect(new NarArchive(directory)));

			expect(error).toBeInstanceOf(UnsupportedNarPathTypeError);
			expect(error).toMatchObject({ path: fifo });
		});
	});

	it('yields the NAR in 1 MiB pieces', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeNarTree(directory);

			const pieces = await collect(new NarArchive(directory));
			const lengths = pieces.map((piece) => piece.byteLength);

			expect(lengths).toStrictEqual([
				...Array.from({ length: 10 }, () => 1024 * 1024),
				11_266_936 - 10 * 1024 * 1024
			]);
		});
	});

	it('is async iterable and hashes its root path', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeFile(pathModule.join(directory, 'file'), 'hello');

			const archive = new NarArchive(directory);
			const iterated = Buffer.concat(await collect(archive));
			const direct = Buffer.concat(await collectNar(directory));

			expect(iterated).toStrictEqual(direct);
			await expect(archive.hash()).resolves.toStrictEqual(
				await hashNar(directory)
			);
		});
	});
});

describe('NarArchive.open', () => {
	it('yields the suffix of the NAR from offsets at and next to every string boundary and from sampled offsets', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeSeekTree(directory);

			const archive = new NarArchive(directory);
			const nar = Buffer.concat(await collect(archive.open(0)));
			const offsets = seekOffsets(nar);
			// Each open waits mostly on file system calls, so several run at once.
			const matches = await mapConcurrently(offsets, 16, (offset) =>
				isSuffix(archive.open(offset), nar, offset)
			);
			const mismatches = offsets.filter((_, index) => matches[index] !== true);

			expect({ checked: offsets.length > 500, mismatches }).toStrictEqual({
				checked: true,
				mismatches: []
			});
		});
	}, 30_000);

	// Root can read a file without read permission, so the test could not tell
	// whether the archive opened the file.
	it.skipIf(process.getuid?.() === 0)(
		'does not open the files that end before the offset',
		async () => {
			await withTemporaryDirectory(
				'cupboard-nar-',
				async (directory) => {
					const unreadable = pathModule.join(directory, 'a-unreadable');
					await writeFile(unreadable, pseudoRandomBytes(200_000, 1));
					await writeFile(pathModule.join(directory, 'b-readable'), 'after');
					const nar = Buffer.concat(await collectNar(directory));
					await chmod(unreadable, 0o000);
					const offset = nar.byteLength - 64;

					const suffix = Buffer.concat(
						await collect(new NarArchive(directory).open(offset))
					);

					expect(suffix).toStrictEqual(nar.subarray(offset));
				},
				{ makeWritableBeforeCleanup: true }
			);
		}
	);
});

describe('toNixBase32', () => {
	it('encodes SHA-256 bytes using the Nix base32 alphabet', () => {
		const emptySha256 = Buffer.from(
			'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
			'hex'
		);

		expect(toNixBase32(emptySha256)).toBe(
			'0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73'
		);
	});
});

describe('NixSha256Hash', () => {
	it('parses valid Nix SHA-256 hashes', () => {
		const hash = NixSha256Hash.parse(
			'sha256:0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73'
		);

		expect(hash.toString()).toBe(
			'sha256:0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73'
		);
	});

	it('rejects invalid hash strings', () => {
		const error = thrownBy(() => NixSha256Hash.parse('sha256:nope'));

		expect(error).toBeInstanceOf(InvalidNixSha256HashError);
		expect(error).toMatchObject({
			name: 'InvalidNixSha256HashError',
			value: 'sha256:nope'
		});
	});

	it('requires a 32-byte digest', () => {
		const error = thrownBy(() => toNixSha256(Buffer.alloc(31)));

		expect(error).toBeInstanceOf(InvalidSha256DigestLengthError);
		expect(error).toMatchObject({
			length: 31,
			name: 'InvalidSha256DigestLengthError'
		});
	});
});

async function rejectionOf(operation: Promise<unknown>): Promise<unknown> {
	try {
		await operation;
	} catch (error) {
		return error;
	}

	return undefined;
}

async function collectNar(path: string): Promise<Buffer[]> {
	return collect(narFromPath(path));
}

async function collect(source: AsyncIterable<Uint8Array>): Promise<Buffer[]> {
	const chunks: Buffer[] = [];

	for await (const chunk of source) {
		chunks.push(Buffer.from(chunk));
	}

	return chunks;
}

// Applies `map` to every item, with at most `limit` calls in progress, and
// returns the results in item order.
async function mapConcurrently<T, R>(
	items: readonly T[],
	limit: number,
	map: (item: T) => Promise<R>
): Promise<R[]> {
	const results: R[] = [];
	let next = 0;
	const worker = async (): Promise<void> => {
		for (let index = next; index < items.length; index = next) {
			next += 1;
			const item = items[index];

			if (item !== undefined) {
				results[index] = await map(item);
			}
		}
	};

	await Promise.all(Array.from({ length: limit }, worker));

	return results;
}

// Whether `source` yields exactly the bytes of `nar` from `offset` to the end.
// It compares each chunk as it arrives, without copying or hashing the suffix.
async function isSuffix(
	source: AsyncIterable<Uint8Array>,
	nar: Buffer,
	offset: number
): Promise<boolean> {
	let position = offset;

	for await (const chunk of source) {
		const expected = nar.subarray(position, position + chunk.byteLength);

		if (!expected.equals(chunk)) {
			return false;
		}

		position += chunk.byteLength;
	}

	return position === nar.byteLength;
}

// Every NAR token is a length-prefixed string padded to a multiple of 8
// bytes. Returns the start of each length prefix, the start and end of each
// string's bytes, the position of each 64 KiB read of a file's contents, and
// the end of the NAR.
function narBoundaries(nar: Buffer): number[] {
	const boundaries: number[] = [];
	let position = 0;

	while (position < nar.byteLength) {
		const length = Number(nar.readBigUInt64LE(position));
		const reads = Array.from(
			{ length: Math.floor(length / 65_536) },
			(_, index) => position + 8 + (index + 1) * 65_536
		);
		boundaries.push(position, position + 8, ...reads, position + 8 + length);
		position += 8 + length + ((8 - (length % 8)) % 8);
	}

	boundaries.push(position);

	return boundaries;
}

// The offsets at and next to each boundary, and a pseudo-random sample of the
// rest.
function seekOffsets(nar: Buffer): number[] {
	const sample = pseudoRandomBytes(4 * 64, 7);
	const view = new DataView(sample.buffer, sample.byteOffset, 4 * 64);
	const offsets = [
		...narBoundaries(nar).flatMap((position) => [
			position - 1,
			position,
			position + 1
		]),
		...Array.from(
			{ length: 64 },
			(_, index) => view.getUint32(index * 4, true) % nar.byteLength
		)
	];

	return [...new Set(offsets)]
		.filter((offset) => offset >= 0 && offset <= nar.byteLength)
		.toSorted((left, right) => left - right);
}

// Files on each side of the 8-byte padding boundary and of the 64 KiB
// synchronous-read limit, an executable, symlinks, an empty directory and a
// file that takes several 64 KiB reads.
async function writeSeekTree(directory: string): Promise<void> {
	const nested = pathModule.join(directory, 'd', 'e');
	await mkdir(nested, { recursive: true });

	for (const [index, size] of narTreeFileSizes.entries()) {
		await writeFile(
			pathModule.join(nested, `f${String(index)}`),
			pseudoRandomBytes(size, index + 1)
		);
	}

	await chmod(pathModule.join(nested, 'f3'), 0o755);
	await symlink('f1', pathModule.join(nested, 'link'));
	await mkdir(pathModule.join(directory, 'empty'));
	await writeFile(
		pathModule.join(directory, 'large'),
		pseudoRandomBytes(300_003, 99)
	);
	await writeFile(pathModule.join(directory, 'z'), 'last');
}

async function narText(path: string): Promise<string> {
	return Buffer.concat(await collectNar(path)).toString('latin1');
}

function narString(value: string): string {
	const bytes = Buffer.from(value, 'utf8');
	const length = Buffer.alloc(8);
	length.writeBigUInt64LE(BigInt(bytes.byteLength));

	return Buffer.concat([
		length,
		bytes,
		Buffer.alloc((8 - (bytes.byteLength % 8)) % 8)
	]).toString('latin1');
}

interface NarFixture {
	readonly sourcePath: string;
	readonly narBytes: Buffer;
	readonly narSize: number;
	readonly narSha256: string;
}

const narFixtureMetadataSchema = z.strictObject({
	storePath: z.string(),
	narSize: z.number(),
	narSha256: z.string()
});

type NarFixtureMetadata = z.infer<typeof narFixtureMetadataSchema>;

async function readNarFixture(name: string): Promise<NarFixture> {
	const fixtureDirectory = pathModule.resolve(
		import.meta.dirname,
		'../../../../tests/fixtures',
		name
	);
	const metadataJson = await readFile(
		pathModule.join(fixtureDirectory, 'metadata.json'),
		'utf8'
	);
	const metadata = parseNarFixtureMetadata(JSON.parse(metadataJson));
	const narBytes = await readFile(
		pathModule.join(fixtureDirectory, 'source.nar')
	);

	return {
		sourcePath: pathModule.join(fixtureDirectory, 'source'),
		narBytes,
		narSize: metadata.narSize,
		narSha256: metadata.narSha256
	};
}

function parseNarFixtureMetadata(value: unknown): NarFixtureMetadata {
	const result = narFixtureMetadataSchema.safeParse(value);

	if (!result.success) {
		throw new InvalidNarFixtureMetadataError(value);
	}

	return result.data;
}

class InvalidNarFixtureMetadataError extends Error {
	constructor(public readonly value: unknown) {
		super('Invalid NAR fixture metadata');
		this.name = 'InvalidNarFixtureMetadataError';
	}
}

const narTreeFileSizes = [0, 1, 7, 8, 9, 100, 4095, 65_535, 65_536, 65_537];

// Nested directories of small files with sizes on each side of the 8-byte
// padding boundary and of the 64 KiB synchronous-read limit, executables,
// symlinks to files and directories, a dangling symlink, an empty directory, a
// non-ASCII name and a file of several mebibytes.
async function writeNarTree(directory: string): Promise<void> {
	for (let index = 0; index < 400; index += 1) {
		const subdirectory = pathModule.join(
			directory,
			`d${String(index % 5)}`,
			`e${String(index % 3)}`
		);
		await mkdir(subdirectory, { recursive: true });
		const file = pathModule.join(subdirectory, `f${String(index)}`);
		await writeFile(
			file,
			pseudoRandomBytes(
				narTreeFileSizes[index % narTreeFileSizes.length] ?? 0,
				index + 1
			)
		);

		if (index % 7 === 0) {
			await chmod(file, 0o755);
		}

		if (index % 11 === 0) {
			await symlink(
				`f${String(index)}`,
				pathModule.join(subdirectory, `l${String(index)}`)
			);
		}
	}

	await writeFile(
		pathModule.join(directory, 'large'),
		pseudoRandomBytes(3 * 1024 * 1024 + 5, 401)
	);
	await mkdir(pathModule.join(directory, 'empty'));
	await symlink('d0', pathModule.join(directory, 'to-directory'));
	await symlink('missing', pathModule.join(directory, 'dangling'));
	await writeFile(pathModule.join(directory, 'naïve'), 'unicode name\n');
}
