import type { Command } from 'commander';

// Help is wrapped to a fixed width and rendered without colour so the reference
// is identical whichever terminal regenerates it.
const helpWidth = 80;

const preamble = `<!-- Generated by \`pnpm update:cli-reference\` from the command definitions. Do not edit by hand. -->

# CLI reference

This page is the \`--help\` output of every \`cupboard\` command. The guides
under [docs/](../README.md) explain when to use each one.`;

interface ReferenceEntry {
	readonly path: readonly string[];
	readonly command: Command;
}

function* walk(
	command: Command,
	path: readonly string[]
): Generator<ReferenceEntry> {
	yield { path, command };

	for (const child of command.commands) {
		// Commander's implicit `help` command documents itself.
		if (child.name() === 'help') {
			continue;
		}

		yield* walk(child, [...path, child.name()]);
	}
}

function renderedHelp(command: Command): string {
	let captured = '';

	command.configureHelp({ helpWidth });
	command.configureOutput({
		getOutHasColors: () => false,
		writeOut: (text) => {
			captured += text;
		}
	});
	// `helpInformation()` omits text added with `addHelpText`, which is written
	// only when help is output.
	command.outputHelp();

	return captured.trimEnd();
}

function anchorFor(path: readonly string[]): string {
	return path.join('-');
}

function renderIndex(entries: readonly ReferenceEntry[]): string {
	return entries
		.slice(1)
		.map(({ path }) => {
			const indent = '  '.repeat(path.length - 2);

			return `${indent}- [\`${path.join(' ')}\`](#${anchorFor(path)})`;
		})
		.join('\n');
}

function renderEntry({ path, command }: ReferenceEntry): string {
	const depth = Math.min(path.length + 1, 6);

	return [
		`${'#'.repeat(depth)} ${path.join(' ')}`,
		'',
		'```text',
		renderedHelp(command),
		'```'
	].join('\n');
}

/**
 * Render the Markdown CLI reference for a freshly built program. Rendering
 * reconfigures each command's help output, so pass a program built for this
 * purpose rather than one that will go on to parse arguments.
 */
export function renderCliReference(program: Command): string {
	const entries = [...walk(program, [program.name()])];

	return `${[preamble, renderIndex(entries), ...entries.map((entry) => renderEntry(entry))].join('\n\n')}\n`;
}
