/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c wrangler.tenant.jsonc --env-file .typegen.tenant.vars --strict-vars false --env-interface TenantEnv --include-runtime false worker-configuration.tenant.d.ts` (hash: 264f820a351f77d5b5d21e4bf6fdbfdd)
interface __BaseEnv_TenantEnv {
	BLOBS: R2Bucket;
	CUPBOARD_DB: D1Database;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_BUCKET_NAME: string;
	R2_SECRET_ACCESS_KEY: string;
	CUPBOARD_OWNER_ISSUER: string;
	CUPBOARD_OWNER_SUBJECT: string;
	CUPBOARD_OWNER_AUDIENCE: string;
	CUPBOARD_AUTH_ISSUER: string;
	CUPBOARD_AUTH_AUDIENCE: string;
	CUPBOARD_COLD_PATH_TTL_SECONDS: string;
	CUPBOARD_DO: DurableObjectNamespace<import("./src/tenant-worker").CupboardServer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/tenant-worker");
		durableNamespaces: "CupboardServer";
	}
	interface Env extends __BaseEnv_TenantEnv {}
}
interface TenantEnv extends __BaseEnv_TenantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_ACCESS_KEY_ID" | "R2_BUCKET_NAME" | "R2_SECRET_ACCESS_KEY" | "CUPBOARD_OWNER_ISSUER" | "CUPBOARD_OWNER_SUBJECT" | "CUPBOARD_OWNER_AUDIENCE" | "CUPBOARD_AUTH_ISSUER" | "CUPBOARD_AUTH_AUDIENCE" | "CUPBOARD_COLD_PATH_TTL_SECONDS">> {}
}
