/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.tenant.jsonc --env-file=.typegen.tenant.vars --include-runtime=false --strict-vars=false --env-interface=TenantEnv worker-configuration.tenant.d.ts` (hash: 24c5d7d1149aef7e26fa2837ad1b87fa)
interface __BaseEnv_TenantEnv {
	BLOBS: R2Bucket;
	CUPBOARD_DB: D1Database;
	MAINTENANCE_QUEUE: Queue;
	CUPBOARD_LOCAL_DEV: string;
	CUPBOARD_COMMIT_SOCKET_CEILING: string;
	CUPBOARD_COMMIT_ENTRY_CREDIT_BUDGET: string;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_BUCKET_NAME: string;
	R2_SECRET_ACCESS_KEY: string;
	PUSH_ID_SIGNING_KEY: string;
	CUPBOARD_AUTH_ISSUER: string;
	CUPBOARD_AUTH_AUDIENCE: string;
	CUPBOARD_COLD_PATH_TTL_SECONDS: string;
	CUPBOARD_DO: DurableObjectNamespace<import("./src/tenant-worker").CupboardServer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/tenant-worker");
		durableNamespaces: "CupboardServer" | "VersionedR2ObjectRollbackGuard";
	}
	interface Env extends __BaseEnv_TenantEnv {}
}
interface TenantEnv extends __BaseEnv_TenantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CUPBOARD_LOCAL_DEV" | "CUPBOARD_COMMIT_SOCKET_CEILING" | "CUPBOARD_COMMIT_ENTRY_CREDIT_BUDGET" | "R2_ACCOUNT_ID" | "R2_ACCESS_KEY_ID" | "R2_BUCKET_NAME" | "R2_SECRET_ACCESS_KEY" | "PUSH_ID_SIGNING_KEY" | "CUPBOARD_AUTH_ISSUER" | "CUPBOARD_AUTH_AUDIENCE" | "CUPBOARD_COLD_PATH_TTL_SECONDS">> {}
}
