/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.typegen.vars --include-runtime=false --strict-vars=false` (hash: 74fd2203aa00359bb0a6c18e4a81de2e)
interface __BaseEnv_Env {
	TENANT_CACHE: KVNamespace;
	CRON_STATE: KVNamespace;
	BLOBS: R2Bucket;
	DEPLOYMENT_RECOVERY: R2Bucket;
	CUPBOARD_DB: D1Database;
	MAINTENANCE_QUEUE: Queue;
	WORKER_VERSION: WorkerVersionMetadata;
	CUPBOARD_RUNTIME_STAGE: string;
	CUPBOARD_DEPLOYMENT_ARTIFACT_ID: string;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_BUCKET_NAME: string;
	R2_SECRET_ACCESS_KEY: string;
	PUSH_ID_SIGNING_KEY: string;
	CUPBOARD_AUTH_ISSUER: string;
	CUPBOARD_AUTH_AUDIENCE: string;
	CUPBOARD_CONTROL_AUDIENCE: string;
	CONTROL_KEY_WRAP_SECRET: string;
	CUPBOARD_SIGNUP_ISSUER: string;
	CUPBOARD_SIGNUP_AUDIENCE: string;
	CUPBOARD_SIGNUP_SECRET: string;
	CUPBOARD_SIGNUP_SUBJECT: string;
	CUPBOARD_LOCAL_DEV: string;
	CUPBOARD_DO: DurableObjectNamespace /* CupboardServer from cupboard-tenant */;
	CUPBOARD_TENANT: Service /* entrypoint CachedTenantReads from cupboard-tenant */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CUPBOARD_RUNTIME_STAGE" | "CUPBOARD_DEPLOYMENT_ARTIFACT_ID" | "R2_ACCOUNT_ID" | "R2_ACCESS_KEY_ID" | "R2_BUCKET_NAME" | "R2_SECRET_ACCESS_KEY" | "PUSH_ID_SIGNING_KEY" | "CUPBOARD_AUTH_ISSUER" | "CUPBOARD_AUTH_AUDIENCE" | "CUPBOARD_CONTROL_AUDIENCE" | "CONTROL_KEY_WRAP_SECRET" | "CUPBOARD_SIGNUP_ISSUER" | "CUPBOARD_SIGNUP_AUDIENCE" | "CUPBOARD_SIGNUP_SECRET" | "CUPBOARD_SIGNUP_SUBJECT" | "CUPBOARD_LOCAL_DEV">> {}
}
