/* eslint-disable */
// Generated by Wrangler by running `wrangler types -c wrangler.tenant.toml --env-interface TenantEnv --include-runtime false worker-configuration.tenant.d.ts` (hash: 466ca564e329c9fca7dfca4430bec178)
interface __BaseEnv_TenantEnv {
	BLOBS: R2Bucket;
	CUPBOARD_DB: D1Database;
	CUPBOARD_AUTH_ISSUER: "cupboard";
	CUPBOARD_AUTH_AUDIENCE: "cupboard";
	CUPBOARD_OWNER_ISSUER: "";
	CUPBOARD_OWNER_SUBJECT: "";
	CUPBOARD_OWNER_AUDIENCE: "";
	CUPBOARD_COLD_PATH_TTL_SECONDS: "";
	R2_ACCOUNT_ID: "";
	R2_ACCESS_KEY_ID: "";
	R2_BUCKET_NAME: "cupboard-blobs";
	R2_SECRET_ACCESS_KEY: "";
	CUPBOARD_DO: DurableObjectNamespace<import("./src/tenant-worker").CupboardServer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/tenant-worker");
		durableNamespaces: "CupboardServer";
	}
	interface Env extends __BaseEnv_TenantEnv {}
}
interface TenantEnv extends __BaseEnv_TenantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CUPBOARD_AUTH_ISSUER" | "CUPBOARD_AUTH_AUDIENCE" | "CUPBOARD_OWNER_ISSUER" | "CUPBOARD_OWNER_SUBJECT" | "CUPBOARD_OWNER_AUDIENCE" | "CUPBOARD_COLD_PATH_TTL_SECONDS" | "R2_ACCOUNT_ID" | "R2_ACCESS_KEY_ID" | "R2_BUCKET_NAME" | "R2_SECRET_ACCESS_KEY">> {}
}
