import { type Operation } from '@cupboard/protocol/grants';

const operationLabels: Readonly<Record<Operation, string>> = {
	'upload:negotiate': 'request publication of paths',
	'upload:preview': 'preview publication of paths',
	'upload:status': 'check publication status',
	'upload:commit': 'complete publication of uploaded paths',
	'upload:confirm': 'confirm paths and extend their retention',
	'attestation:negotiate': 'request attestation attachment',
	'attestation:attach': 'attach attestations',
	'root:set': 'set retention roots',
	'root:attach': 'add paths to retention roots',
	'root:list': 'list retention roots',
	'root:remove': 'remove retention roots',
	'cache:read': 'read cache information',
	'cache:content-read': 'read cached content',
	'view:content-read': 'read cached content',
	'cache:create': 'create caches',
	'cache:update': 'change cache settings',
	'cache:retire': 'change automatic cache retirement',
	'cache:close': 'close caches',
	'cache:reopen': 'reopen caches',
	'cache:delete': 'remove caches',
	'cache:list': 'list caches',
	'cache:defaults-read': 'read default cache settings',
	'cache:defaults-update': 'change default cache settings',
	'narinfo:delete': 'delete cached paths',
	'gc:run': 'remove unretained paths',
	'stats:read': 'read storage statistics',
	'check:run': 'check cache integrity',
	'verification:run': 'verify stored cache files',
	'signing-key:list': 'list cache signing keys',
	'signing-key:rotate': 'rotate cache signing keys',
	'signing-key:retire': 'retire cache signing keys or cancel their rotation',
	'auth-key:list': 'list tenant sign-in keys',
	'auth-key:rotate': 'rotate tenant sign-in keys',
	'auth-key:retire': 'retire tenant sign-in keys',
	'session:list': 'list tenant sign-in sessions',
	'session:revoke': 'revoke tenant sign-in sessions',
	'oidc-trust:list': 'list tenant trust rules',
	'oidc-trust:read': 'read tenant trust rules',
	'oidc-trust:add': 'add or extend tenant trust rules',
	'oidc-trust:remove': 'remove tenant trust rules',
	'policy:list': 'list attestation trust policies',
	'policy:remove': 'remove attestation trust policies',
	'reuse-view:list': 'list reuse views',
	'reuse-view:set': 'change reuse views',
	'reuse-view:remove': 'remove reuse views',
	'control:check': 'check deployment health',
	'instance:read': 'read deployment settings',
	'instance:initialise': 'configure deployment settings',
	'control-key:list': 'list operator sign-in keys',
	'control-key:rotate': 'rotate operator sign-in keys',
	'control-key:retire': 'retire operator sign-in keys',
	'control-session:list': 'list operator sign-in sessions',
	'control-session:revoke': 'revoke operator sign-in sessions',
	'tenant:list': 'list tenants',
	'tenant:create': 'create tenants',
	'tenant:suspend': 'suspend tenants',
	'tenant:resume': 'resume tenants',
	'tenant:remove': 'remove tenants',
	'tenant:rotate-read-credential': 'replace tenant read credentials',
	'tenant:clear-read-credential': 'remove tenant read credentials',
	'tenant:rotate-cache-read-credential': 'replace cache read credentials',
	'tenant:clear-cache-read-credential': 'remove cache read credentials',
	'tenant:read-quota': 'read tenant storage quotas',
	'tenant:set-quota': 'change tenant storage quotas',
	'membership:rebuild': 'refresh reuse-view cache membership',
	'deployment:read': 'read deployment status',
	'local-step:read': 'read tenant update status',
	'local-step:wake': 'retry tenant updates',
	'control-oidc-trust:list': 'list operator trust rules',
	'control-oidc-trust:read': 'read operator trust rules',
	'control-oidc-trust:add': 'add operator trust rules',
	'control-oidc-trust:remove': 'remove operator trust rules'
};

/**
Describes one granted operation without combining distinct permissions.
*/
export function humanOperation(operation: Operation): string {
	return operationLabels[operation];
}
