import { createHash } from 'node:crypto';
import { chmod, readFile, symlink, writeFile } from 'node:fs/promises';
import pathModule from 'node:path';

import { describe, expect, it } from 'vitest';

import { withTemporaryDirectory } from '../../../tests/support/filesystem.ts';

import {
	hashNar,
	InvalidNixSha256HashError,
	InvalidSha256DigestLengthError,
	NarArchive,
	narFromPath,
	NixSha256Hash,
	toNixBase32,
	toNixSha256
} from './nar.ts';

describe('narFromPath', () => {
	it('serialises an empty directory', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await expect(narText(directory)).resolves.toBe(
				['nix-archive-1', '(', 'type', 'directory', ')']
					.map((value) => narString(value))
					.join('')
			);
		});
	});

	it('sorts directory entries by byte order', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeFile(pathModule.join(directory, 'b'), 'second');
			await writeFile(pathModule.join(directory, 'a'), 'first');

			const text = await narText(directory);

			expect(text.indexOf(narString('a'))).toBeLessThan(
				text.indexOf(narString('b'))
			);
		});
	});

	it('serialises symlinks and executable files', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			const file = pathModule.join(directory, 'run');
			await writeFile(file, 'hello');
			await chmod(file, 0o755);
			await symlink('run', pathModule.join(directory, 'link'));

			const text = await narText(directory);

			expect(text).toContain(narString('executable'));
			expect(text).toContain(narString('symlink'));
			expect(text).toContain(narString('target'));
			expect(text).toContain(narString('run'));
		});
	});
});

describe('hashNar', () => {
	it('returns a Nix base32 sha256 hash and NAR size', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeFile(pathModule.join(directory, 'file'), 'hello');

			const bytes = Buffer.concat(await collectNar(directory));
			const expectedHash = toNixSha256(
				createHash('sha256').update(bytes).digest()
			);

			await expect(hashNar(directory)).resolves.toStrictEqual({
				narHash: expectedHash,
				narSize: bytes.byteLength
			});
		});
	});

	it('matches a NAR fixture generated by nix-store --dump', async () => {
		const fixture = await readNarFixture('simple');
		const expectedHash = toNixSha256(Buffer.from(fixture.narSha256, 'hex'));
		const actualBytes = Buffer.concat(await collectNar(fixture.sourcePath));

		expect(actualBytes).toStrictEqual(fixture.narBytes);
		await expect(hashNar(fixture.sourcePath)).resolves.toStrictEqual({
			narHash: expectedHash,
			narSize: fixture.narSize
		});
	});
});

describe('NarArchive', () => {
	it('is async iterable and hashes its root path', async () => {
		await withTemporaryDirectory('cupboard-nar-', async (directory) => {
			await writeFile(pathModule.join(directory, 'file'), 'hello');

			const archive = new NarArchive(directory);
			const iterated = Buffer.concat(await collect(archive));
			const direct = Buffer.concat(await collectNar(directory));

			expect(iterated).toStrictEqual(direct);
			await expect(archive.hash()).resolves.toStrictEqual(
				await hashNar(directory)
			);
		});
	});
});

describe('toNixBase32', () => {
	it('encodes SHA-256 bytes using the Nix base32 alphabet', () => {
		const emptySha256 = Buffer.from(
			'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
			'hex'
		);

		expect(toNixBase32(emptySha256)).toBe(
			'0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73'
		);
	});
});

describe('NixSha256Hash', () => {
	it('parses valid Nix SHA-256 hashes', () => {
		const hash = NixSha256Hash.parse(
			'sha256:0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73'
		);

		expect(hash.toString()).toBe(
			'sha256:0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73'
		);
	});

	it('rejects invalid hash strings', () => {
		expect(() => NixSha256Hash.parse('sha256:nope')).toThrow(
			InvalidNixSha256HashError
		);
	});

	it('requires a 32-byte digest', () => {
		expect(() => toNixSha256(Buffer.alloc(31))).toThrow(
			InvalidSha256DigestLengthError
		);
	});
});

async function collectNar(path: string): Promise<Buffer[]> {
	return collect(narFromPath(path));
}

async function collect(source: AsyncIterable<Uint8Array>): Promise<Buffer[]> {
	const chunks: Buffer[] = [];

	for await (const chunk of source) {
		chunks.push(Buffer.from(chunk));
	}

	return chunks;
}

async function narText(path: string): Promise<string> {
	return Buffer.concat(await collectNar(path)).toString('latin1');
}

function narString(value: string): string {
	const bytes = Buffer.from(value, 'utf8');
	const length = Buffer.alloc(8);
	length.writeBigUInt64LE(BigInt(bytes.byteLength));

	return Buffer.concat([
		length,
		bytes,
		Buffer.alloc((8 - (bytes.byteLength % 8)) % 8)
	]).toString('latin1');
}

interface NarFixture {
	readonly sourcePath: string;
	readonly narBytes: Buffer;
	readonly narSize: number;
	readonly narSha256: string;
}

interface NarFixtureMetadata {
	readonly narSize: number;
	readonly narSha256: string;
}

async function readNarFixture(name: string): Promise<NarFixture> {
	const fixtureDirectory = pathModule.resolve(
		import.meta.dirname,
		'../../../tests/fixtures',
		name
	);
	const metadata = parseNarFixtureMetadata(
		JSON.parse(
			await readFile(pathModule.join(fixtureDirectory, 'metadata.json'), 'utf8')
		)
	);
	const narBytes = await readFile(
		pathModule.join(fixtureDirectory, 'source.nar')
	);

	return {
		sourcePath: pathModule.join(fixtureDirectory, 'source'),
		narBytes,
		narSize: metadata.narSize,
		narSha256: metadata.narSha256
	};
}

function parseNarFixtureMetadata(value: unknown): NarFixtureMetadata {
	if (!isNarFixtureMetadata(value)) {
		throw new InvalidNarFixtureMetadataError(value);
	}

	return value;
}

function isNarFixtureMetadata(value: unknown): value is NarFixtureMetadata {
	if (typeof value !== 'object' || value === null) {
		return false;
	}

	const record = value as Record<string, unknown>;

	return (
		typeof record.narSize === 'number' && typeof record.narSha256 === 'string'
	);
}

class InvalidNarFixtureMetadataError extends Error {
	constructor(public readonly value: unknown) {
		super('Invalid NAR fixture metadata');
		this.name = 'InvalidNarFixtureMetadataError';
	}
}
