import type { InvocationId } from '@cupboard/protocol/build';

export interface HookScriptOptions {
	readonly invocationId: InvocationId;
	readonly helperPath: string;
	readonly socketPath: string;
}

// The values baked into the script are wrapped in single quotes; an embedded
// single quote is spelt with the standard close-quote, escaped-quote,
// reopen-quote sequence so any path the supervisor planned survives intact.
function shellQuote(value: string): string {
	return `'${value.replaceAll("'", String.raw`'\''`)}'`;
}

/**
 * The event line the generated script's `printf` produces, composed the same
 * way: `OUT_PATHS` split on spaces, each path wrapped in JSON quotes. Store
 * paths carry no characters needing JSON escaping, so plain quoting yields a
 * valid `buildEventSchema` document.
 */
export function composeBuildEventLine(
	invocationId: InvocationId,
	derivationPath: string,
	outPaths: string
): string {
	const outputPaths = outPaths
		.split(' ')
		.filter((outputPath) => outputPath !== '')
		.map((outputPath) => `"${outputPath}"`)
		.join(',');

	return `{"version":1,"invocationId":"${invocationId}","derivation":"${derivationPath}","outputPaths":[${outputPaths}]}`;
}

/**
 * The `/bin/sh` post-build hook for one invocation. It runs as the store's
 * user with the daemon's environment, so it relies only on `/bin/sh`, shell
 * builtins and the absolute paths baked in here: it splits `OUT_PATHS` on the
 * spaces Nix guarantees, composes the single versioned event line, and execs
 * the compiled helper with the line on standard input. One printf-to-exec
 * pipeline keeps the per-derivation start-up cost to the shell itself.
 */
export function renderHookScript(options: HookScriptOptions): string {
	const invocationId = shellQuote(options.invocationId);
	const helper = shellQuote(options.helperPath);
	const socket = shellQuote(options.socketPath);

	return String.raw`#!/bin/sh
# Generated by cupboard for one build-push invocation. A delivery failure
# warns and exits zero: a non-zero hook exit would fail the derivation's
# goal, and final reconciliation republishes anything the event stream
# lost.
# Store-path names may carry glob characters, so word-splitting runs with
# pathname expansion off.
set -f
out=
for path in $OUT_PATHS; do
	if [ -z "$out" ]; then
		out="\"$path\""
	else
		out="$out,\"$path\""
	fi
done
printf '{"version":1,"invocationId":"%s","derivation":"%s","outputPaths":[%s]}\n' ${invocationId} "$DRV_PATH" "$out" | exec ${helper} ${socket}
`;
}
