import { buildEventSchema, invocationIdSchema } from '@cupboard/protocol/build';
import { describe, expect, it } from 'vitest';

import { composeBuildEventLine, renderHookScript } from './hook-script.ts';

const invocationId = invocationIdSchema.parse('invocation-1');
const outputPath = '/nix/store/0123456789abcdfghijklmnpqrsvwxyz-app';
const otherOutputPath = '/nix/store/3123456789abcdfghijklmnpqrsvwxyz-lib';
const derivation = '/nix/store/4123456789abcdfghijklmnpqrsvwxyz-app.drv';

function expectedScript(quoted: {
	readonly invocationId: string;
	readonly helperPath: string;
	readonly socketPath: string;
}): string {
	return String.raw`#!/bin/sh
# Generated by cupboard for one build-push invocation. A delivery failure
# warns and exits zero: a non-zero hook exit would fail the derivation's
# goal, and final reconciliation republishes anything the event stream
# lost.
# Store-path names may carry glob characters, so word-splitting runs with
# pathname expansion off.
set -f
out=
for path in $OUT_PATHS; do
	if [ -z "$out" ]; then
		out="\"$path\""
	else
		out="$out,\"$path\""
	fi
done
printf '{"version":1,"invocationId":"%s","derivation":"%s","outputPaths":[%s]}\n' ${quoted.invocationId} "$DRV_PATH" "$out" | exec ${quoted.helperPath} ${quoted.socketPath}
`;
}

describe('renderHookScript', () => {
	it.each([
		{
			name: 'a runner-style runtime directory',
			helperPath: '/opt/cupboard/cupboard-hook-relay',
			socketPath: '/runner/tmp/cupboard/invocation-1/hook.sock'
		},
		{
			name: 'a store-installed helper',
			helperPath:
				'/nix/store/1123456789abcdfghijklmnpqrsvwxyz-cupboard/libexec/cupboard/cupboard-hook-relay',
			socketPath: '/run/user/1000/cupboard/invocation-1/hook.sock'
		}
	])('renders the exact script for $name', ({ helperPath, socketPath }) => {
		expect(renderHookScript({ invocationId, helperPath, socketPath })).toBe(
			expectedScript({
				invocationId: `'${invocationId}'`,
				helperPath: `'${helperPath}'`,
				socketPath: `'${socketPath}'`
			})
		);
	});

	it('holds an embedded single quote through shell quoting', () => {
		const script = renderHookScript({
			invocationId,
			helperPath: "/opt/o'brien/cupboard-hook-relay",
			socketPath: '/tmp/cupboard/invocation-1/hook.sock'
		});

		expect(script).toBe(
			expectedScript({
				invocationId: `'${invocationId}'`,
				helperPath: String.raw`'/opt/o'\''brien/cupboard-hook-relay'`,
				socketPath: "'/tmp/cupboard/invocation-1/hook.sock'"
			})
		);
	});
});

describe('composeBuildEventLine', () => {
	it.each([
		{
			name: 'a single output path',
			outPaths: outputPath,
			expectedOutputs: [outputPath]
		},
		{
			name: 'two space-separated output paths',
			outPaths: `${outputPath} ${otherOutputPath}`,
			expectedOutputs: [outputPath, otherOutputPath]
		},
		{
			name: 'a trailing separator',
			outPaths: `${outputPath} `,
			expectedOutputs: [outputPath]
		}
	])('composes a valid event for $name', ({ outPaths, expectedOutputs }) => {
		const line = composeBuildEventLine(invocationId, derivation, outPaths);

		expect(buildEventSchema.parse(JSON.parse(line))).toStrictEqual({
			version: 1,
			invocationId,
			derivation,
			outputPaths: expectedOutputs
		});
	});
});
