import type { InvocationId } from '@cupboard/protocol/build';

export interface HookScriptOptions {
	readonly invocationId: InvocationId;
	readonly helperPath: string;
	readonly socketPath: string;
	readonly rootLinkDirectory?: string;
}

// The values baked into the script are wrapped in single quotes; an embedded
// single quote is spelt with the standard close-quote, escaped-quote,
// reopen-quote sequence so any path the supervisor planned survives intact.
function shellQuote(value: string): string {
	return `'${value.replaceAll("'", String.raw`'\''`)}'`;
}

/**
 * The event line the generated script's `printf` produces. Nix supplies
 * `OUT_PATHS` as a space-separated list. The function wraps each path in JSON
 * quotes; store paths contain no characters that require JSON escaping.
 */
export function composeBuildEventLine(
	invocationId: InvocationId,
	derivationPath: string,
	outPaths: string
): string {
	const outputPaths = outPaths
		.split(' ')
		.filter((outputPath) => outputPath !== '')
		.map((outputPath) => `"${outputPath}"`)
		.join(',');

	return `{"version":1,"invocationId":"${invocationId}","derivation":"${derivationPath}","outputPaths":[${outputPaths}]}`;
}

/**
 * The `/bin/sh` post-build hook for one invocation. It runs as the store's
 * user. Nix supplies `OUT_PATHS` as a space-separated list, which the hook
 * converts into one versioned event. The hook then invokes the compiled helper
 * with the event on standard input. For a daemonless run, it first creates a GC
 * root for each completed output through the local store.
 */
export function renderHookScript(options: HookScriptOptions): string {
	const invocationId = shellQuote(options.invocationId);
	const helper = shellQuote(options.helperPath);
	const socket = shellQuote(options.socketPath);
	const rootSetup =
		options.rootLinkDirectory === undefined
			? 'root_directory=\noutput_protection=\n'
			: `root_directory=${shellQuote(options.rootLinkDirectory)}
output_protection=
`;
	const protectPath =
		options.rootLinkDirectory === undefined
			? ''
			: `	path_name=\${path##*/}
	path_hash=\${path_name%%-*}
	root="$root_directory/$path_hash"
	if ! nix-store --realise "$path" --add-root "$root" >/dev/null && [ ! -L "$root" ]; then
		output_protection=',"outputProtection":"failed"'
	fi
`;

	return String.raw`#!/bin/sh
# Generated by cupboard for one build-push invocation. A delivery failure
# warns and exits zero because a non-zero hook exit would fail the
# derivation's goal.
# Store-path names may carry glob characters, so word-splitting runs with
# pathname expansion off.
set -f
${rootSetup}out=
for path in $OUT_PATHS; do
${protectPath}	if [ -z "$out" ]; then
		out="\"$path\""
	else
		out="$out,\"$path\""
	fi
done
if [ -n "$output_protection" ]; then
	printf '%s\n' 'cupboard: failed to protect every completed output from garbage collection. Cupboard will try to publish the outputs that remain after the build.' >&2
fi
printf '{"version":1,"invocationId":"%s","derivation":"%s","outputPaths":[%s]%s}\n' ${invocationId} "$DRV_PATH" "$out" "$output_protection" | exec ${helper} ${socket}
`;
}
