name: commit-messages

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: underwhelmingperformance/wrapscallion@b1f531d8519330d6cadaa2b25efbca742c06d36f # v0.2.0
